target: Default
test_size: 0.2
random_state: 20

features:
  numerical:
    - Age
    - Income
    - LoanAmount
    - CreditScore
    - MonthsEmployed
    - NumCreditLines
    - InterestRate
    - LoanTerm
    - DTIRatio
  categorical:
    - Education
    - EmploymentType
    - MaritalStatus
    - HasMortgage
    - HasDependents
    - LoanPurpose
    - HasCoSigner

models:
  logistic_regression:
    C: 1.0
    max_iter: 200
  decision_tree:
    max_depth: 6
    min_samples_split: 4
  random_forest:
    n_estimators: 200
    max_depth: 8
    min_samples_split: 4
